---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
stringData:
  password: VMware1!
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC7TCCAdWgAwIBAgIGAZkRpY5iMA0GCSqGSIb3DQEBCwUAMCgxFTATBgNVBAMM
    DFZNd2FyZS1EQi1DQTEPMA0GA1UECgwGVk13YXJlMB4XDTI1MDgzMTIyMTQ0NloX
    DTM1MDkwMzIyMTQ0NlowKDEVMBMGA1UEAwwMVk13YXJlLURCLUNBMQ8wDQYDVQQK
    DAZWTXdhcmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlpL3XvqE1
    qxO78rSSnVKhXIa9VFhTmjFNdph0tk2G4jYNL9m+a7V2nTPtvF67LlNEiPBL96wL
    fkqYHdCdq6gaAwVzMYy3PXN74xY0m2Wr0/OW/0LAiGji9aMfrQW33DZI8FHNtv3R
    LYM5tPLQiU7vM6IoMpodzBs3O80+jxWAs23FL8f3a/h3gbbSiXbY+6PqJRwXCpHF
    4evlsbLVcMcYPFlr3exHr+VJH7PgaazX/xwBe1nG47YekKMyMn+743ucaYTpQini
    EQvdRQ6sqw90JS88kIH/b8NGb5jtM7OUb3aOfYpCVi+n9xpOozfFatoJ74PI7EFK
    E25QqcPZXRHVAgMBAAGjHTAbMAsGA1UdDwQEAwIBBjAMBgNVHRMEBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4IBAQCXJP5Qjhd0STpqdmCEuJt0oDWzrVXbUR5nyNgb6EDu
    UqJyD0GrQtZH75KXNlZDN0Sk5kAwjJkB/dEK+s+yfIwLALsR1CmsxEltUtI1N13l
    jJJPOg4PD1dWqxblr8surb0yDjlZc87Vdn4YitQtqilvi+qoBjhkv5zYWF6/hNM8
    aJDkQcf1BDW2AGh+y8eoD395CS3tUocA1KgLUxaaLy48L3T8hovuSSuUIOA2moyy
    /KiYEte87gagMBVUVCX0Xq01FaFRW4CCM/l6ajdWIDLZxtZ5KX0KFIsuoJXhpbGP
    HlW10sVpPH+4N/+SAXag4Nx7+qzzQnsHmmgWa2bbI1P5
    -----END CERTIFICATE-----