---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-trust-bundle-for-harbor
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFwTCCA6mgAwIBAgIUQo665eqszQPTq+EwW+dJns+zR18wDQYJKoZIhvcNAQEN
    BQAwcDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcM
    CVBhbG8gQWx0bzENMAsGA1UECgwEQUNNRTEOMAwGA1UECwwFTGVnYWwxGTAXBgNV
    BAMMEHJlZ2lzdHJ5LnZjZi5sYWIwHhcNMjUwODA5MjIzODQyWhcNMzUwODA3MjIz
    ODQyWjBwMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UE
    BwwJUGFsbyBBbHRvMQ0wCwYDVQQKDARBQ01FMQ4wDAYDVQQLDAVMZWdhbDEZMBcG
    A1UEAwwQcmVnaXN0cnkudmNmLmxhYjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBANLo0O/Sn/JYgqTVtzjq6aFqjbRmpPTK/zd+FYqyg8WpizWAmpDWTe9L
    t42/62Y2Ceb/CZc/XedVFKgY1IDWz5+RhSr31+ss2yZF/k1CS14FeNi4lnx8SgeV
    10BsL5EYQflWaguZPr5H5CZYdCLbcB+kQq9DVqeQko+vhXat2iHrtJ8Ahehm5o0j
    IXpgCMXKzF3epR4YTOKalB+fM+rDFttAB7xc1ksOftmP0RDYAJzQN+Idue5HYwjR
    bAivwHoCkzEHmg/5rKMA0+RMB48iPU3PpTXP4jpMwZmC7ADtOoclztCf/nQLhfDd
    qjmrgYVisqNW4dyQMtVpAXpEcMF+UsdUd+kqeQXrJKeJjPzb0Nby+1QPOITEi/kw
    EMqwGPZthzn/8FIt0NgMN50Q82Z6b1kIZyOhAhgLwiyH272D/3mauC0IPupRpDpQ
    BxNyHvVqGcBglzNxvgVMhqbGZbAVPMquE/J1k8LVWWGZ/hBRmsZsyZZu+sfShiI2
    YKI5AQDnWliLVaRdxF/o7U3cQoZ6S64HXdF4tCEn9vJccp730GsVPVI1qk2doAFE
    2Wk+6PYyBavRHHeMiKnq+r9VbGpsJEa3w1UBFvzc53V06YGiCCz1z9JxpT2AO0Xv
    9uqv5/vHOqRMJMXdjDKjHq06oD+XG6ls/zAp7dSAN5kNPiTD6KVFAgMBAAGjUzBR
    MB0GA1UdDgQWBBQb0RsudQL4QQ5362HXlBy0o9aH4zAfBgNVHSMEGDAWgBQb0Rsu
    dQL4QQ5362HXlBy0o9aH4zAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBDQUA
    A4ICAQCfn5RYi4dP+MUvhWHPDcoYg1gmOGA8p2NXboVjzRa9WAYTmyZI6NDDy67g
    ELhaYr4u1pyhjbmbszzqfR8gJIRnmBCw+5bovBOMTei9pBHqIJoAbzexJFUeYBug
    FEqtOC9J/Na8X6ZqlstmXA4AzZn4LWg8JAZ0e3narTev5CEnlVUlCOvy/1TgpQ8G
    kn50vULaw6DOxy0rooA3kdtTjhKCoDFtRUCk26HQ8tWeK1oJOvmMk5Zar385JKnQ
    7i5k9jnHD+w3m8LJDXTO1vDdCxIowvjDBmaZVEW2jBhGQoRsB3PafknpQuUtjGaD
    D1k/mSN/wmySRVYEG+hVFdRxeOxx8R3kQezjdOpx0EtgnDCYYGPIdJNz2pybrNyE
    IxJQURw1CqjRh5BRL4botk2M7blv7HZSnjumgO5mnySeYIJ918zSbhYghxkpYxTv
    SPwq4TX/eUFTqaye6YQiiOwrJMXMsVsapsORqjpr3U/SSiebKQmAOL3P2+JKzFpa
    hI3fJQCzvddeJ70yYhkBgJOicvfuYS3iqg0vCNpsaEC1VQarQdtocxVMRLAVpnMf
    7eGKRC4+J7axFUjgfB0EFAZWno6DaF4hk9ZRrzuuNzyUOJezd/7ggOjnSURyx+GI
    w0Pnburl6Kd2YmT3T4zEAIsn538jyGtMLnq5uCr3XETdSuscgw==
    -----END CERTIFICATE-----